name: CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Delete gh-pages branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          branches: gh-pages
      - name: Delete previous deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GH_PAGES_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
  deploy:
    needs: cleanup
    runs-on: ubuntu-latest
    permissions:
      pages: write
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo "#####################"
          echo "Preparing environment"
          echo "#####################"
          echo
          echo "###############"
          echo "Installing node"
          echo "###############"
          sudo apt install nodejs || { echo "Install node failed"; exit 1; }
          echo "node version installed: $(node -v)"
          echo
          echo "##############"
          echo "Installing npm"
          echo "##############"
          sudo apt install npm || { echo "Install npm failed"; exit 1; }
          echo "npm version installed: $(npm -v)"
          echo
          echo "#######################"
          echo "Installing dependencies"
          echo "#######################"
          npm install || { echo "Install dependencies failed"; exit 1; }
          echo
          echo "######################################"
          echo "Environment preparation was successful"
          echo "######################################"
          echo
          echo "--------------------------------------"
          echo
          echo "############################"
          echo "Building ptlux1517.github.io"
          echo "############################"
          echo
          echo "###############"
          echo "Running webpack"
          echo "###############"
          npm run build || { echo "Webpack failed"; exit 1; }
          echo
          echo "####################"
          echo "Build was successful"
          echo "####################"
          exit 0
      - name: Push build to gh-pages branch
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          repository: 'PTLux1517/PTLux1517.github.io'
      - name: Deploy gh-pages branch #see api docs here: https://docs.github.com/en/rest/pages/pages?apiVersion=2022-11-28#create-a-github-pages-site
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAGES_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/PTLux1517/PTLux1517.github.io/pages \
          -d '{"source":{"branch":"gh-pages"}}'